### ISSUE TITLE
Should /payloadCreation endpoints be GET or POST?

### ISSUE THREAD

**Issue by christroutner** [Bitcoin-com/rest.bitcoin.com#149]
The v1 implementation of the `/payloadCreation` endpoints made them POST endpoints, with all parameters being passed in through the *URL params*.

The main advantage of using POST is to pass parameters in through the *body*, as opposed to the *URL* or *query* parameters. Ideally, POST calls are used for changing data on the server. 

The functionality of the endpoint calls are to get a partial transaction HEX used to construct a Wormhole transaction. Philosophically, this is more inline with a GET, than a POST. However, some of the calls are quite verbose, and could benefit from the efficiency of passing parameters in the `body` of a POST call. Switching to a GET call would allow load balancers to cache the calls, which would improve scaling and efficiency.

My suggestion is to refactor the `/payloadCreation` endpoints as GET, and maintain the current implementation of passing parameters as `URL` parameters. This represents a trivial code change, but brings the implementation more in-line with RESTful best practices.

**Comment by christroutner** [comment]
This feeds into Issue #50

**Comment by cgcardona** [comment]
I decided to keep them as POST for now. This is resolved in https://github.com/Bitcoin-com/rest.bitcoin.com/pull/168
