### ISSUE TITLE
Port Freeze and Unfreeze to v2

### ISSUE THREAD

**Issue by christroutner** [Bitcoin-com/rest.bitcoin.com#165]
The scope of this issue to port the freeze and unfreeze functionality into rest.bitcoin.com v2. This includes both the route handlers and making the swagger UI work. This issue was broken off from Issue #156.

- `/dataRetrieval/frozenBalance/{address}/{propertyId}` - default input uses invalid address
- `/dataRetrieval/frozenBalanceForAddress/{address}` - default input uses invalid address
- `/dataRetrieval/frozenBalanceForId/{propertyId}` - default input is not a managed token
- `/payloadCreation/freeze/{toAddress}/{propertyId}` - default input causes an error
- `/payloadCreation/unfreeze/{toAddress}/{propertyId}` - default input causes an error

**Comment by christroutner** [comment]
Note: With regard to the swagger UI, this issue applies to both testnet and mainnet. Both of the fixture files need to be updated with working examples.

**Comment by cgcardona** [comment]
Wormhole REST is now deprecated. Closing issue.
