### ISSUE TITLE
Create bulk endpoint for listing slp tokens by Id

### ISSUE THREAD

**Issue by cgcardona** [Bitcoin-com/rest.bitcoin.com#266]
Similar to our other `GET` for single and `POST` for bulk endpoints we should add a `POST` request for getting SLP tokens by token id.

**Comment by christroutner** [comment]
## Overview
The scope of this task is to add a `POST` endpoint to create a bulk-upload version of the existing `GET` call [slp/list/:tokenID](https://rest.bitcoin.com/#/slp/listSingle). The GET call is used for looking up details for tokens one-at-a-time. The POST endpoint would allow an array of token IDs to be passed, to look up several at once.

An example of a similar endpoint using this scheme is the GET and POST endpoints for `block/detailsByHash`:
- GET `block/detailsByHash` [user interface](https://rest.bitcoin.com/#/block/detailsHashSingle)
- GET `block/detailsByHash` [source code](https://github.com/Bitcoin-com/rest.bitcoin.com/blob/master/src/routes/v2/block.ts#L75-L107)
- GET `block/detailsByHash` [unit tests](https://github.com/Bitcoin-com/rest.bitcoin.com/blob/master/src/routes/v2/block.ts#L75-L107)

- POST `block/detailsByHash` [user interface](https://rest.bitcoin.com/#/block/detailsHashBulk)
- POST `block/detailsByHash` [source code](https://github.com/Bitcoin-com/rest.bitcoin.com/blob/master/src/routes/v2/block.ts#L109-L171)
- POST `block/detailsByHash` [unit tests](https://github.com/Bitcoin-com/rest.bitcoin.com/blob/master/test/v2/block.js#L167-L339)
