### ISSUE TITLE
Create single endpoint for sendRawTransaction

### ISSUE THREAD

**Issue by cgcardona** [Bitcoin-com/rest.bitcoin.com#281]
To match our other single/bulk endpoints we need a `GET` for single sendRawTransaction.

More info: https://rest.bitcoin.com/#/rawtransactions/sendRawTransaction

**Comment by christroutner** [comment]
This issue changes the scope of Issue #273. Need clarification on the appropriate approach. Do we:
- Add a GET call to complement the existing POST call (this Issue)
- Keep the existing single POST call and return a string for a single input? (Issue #273)

**Comment by cgcardona** [comment]
You're correct. Let's keep the single sendRawTransaction a `POST` which returns a single string and create a new bulk endpoint which is also `POST` and returns an array of strings.

**Comment by christroutner** [comment]
Need a little more clarification. The scope of #273 is:
- When a single hex is passed to POST `sendRawTransaction()`, it returns a string.
- When an array of hexes are passed to POST `sendRawTransaction()`, it returns an array

So both behaviors would be encapsulated in the existing POST endpoint.

I'm confused by the instruction to create a second POST endpoint. We would need to create a new URL for a new bulk endpoint. We can't have two handlers for the same POST endpoint.

I'm going to move forward with retrofitting the existing POST endpoint to service both behaviors, as described above.

**Comment by christroutner** [comment]
Got additional clarification from Gabriel. We will move the single element call to a GET call with a url parameter. The behavior of the POST endpoint will stay the same.
