### ISSUE TITLE
Create Bulk endpoint for converting slp addresses

### ISSUE THREAD

**Issue by cgcardona** [Bitcoin-com/rest.bitcoin.com#291]
Similar to our other GET/Single and POST/Bulk endpoints we need a POST/Bulk endpoint for converting slp addresses.

https://rest.bitcoin.com/#/slp/slpAddressConvert

**Comment by christroutner** [comment]
## Overview
The scope of this task is to add a `POST` endpoint to create a bulk-upload version of the existing `GET` call [slp/slpAddressConvert](https://rest.bitcoin.com/#/slp/slpAddressConvert). The GET call is used for converting an address to the different types of address format one-at-a-time. The POST endpoint would allow an array of addresses to be passed, to do the conversion on many at once.

An example of a similar endpoint using this scheme is the GET and POST endpoints for `block/detailsByHash`:
- GET `block/detailsByHash` [user interface](https://rest.bitcoin.com/#/block/detailsHashSingle)
- GET `block/detailsByHash` [source code](https://github.com/Bitcoin-com/rest.bitcoin.com/blob/master/src/routes/v2/block.ts#L75-L107)
- GET `block/detailsByHash` [unit tests](https://github.com/Bitcoin-com/rest.bitcoin.com/blob/master/src/routes/v2/block.ts#L75-L107)

- POST `block/detailsByHash` [user interface](https://rest.bitcoin.com/#/block/detailsHashBulk)
- POST `block/detailsByHash` [source code](https://github.com/Bitcoin-com/rest.bitcoin.com/blob/master/src/routes/v2/block.ts#L109-L171)
- POST `block/detailsByHash` [unit tests](https://github.com/Bitcoin-com/rest.bitcoin.com/blob/master/test/v2/block.js#L167-L339)
