### ISSUE TITLE
TXID token quantity lookup endpoint needed for SLP

### ISSUE THREAD

**Issue by christroutner** [Bitcoin-com/rest.bitcoin.com#301]
Currently it's possible to validate a TXID, but it's not possible to lookup the quantity of tokens transferred via TXID. The only way to look up token quantities is by address.

The scope of this Issue is to either add a REST endpoint to do this, or to code an endpoint in SLP SDK to compensate for this lack of endpoint.

**Comment by christroutner** [comment]
From James Cramer:

> At the moment you have to first check that the txid is a valid txn, then parse the op_return data using the SLP class.

> There’s a method called something like SLP.parseSlpOutputScript(buffer)

**Comment by christroutner** [comment]
Did some investigation on this feature. 

The goal is to great an endpoint that takes TXID as input and returns an object with the following properties:
- `sentFrom`
- `sentTo`
- `quantity`
- `symbol`
- `tokenId`

The exploratory code I developed lives in the [ct-token-transfer branch](https://github.com/Bitcoin-com/rest.bitcoin.com/compare/stage...Bitcoin-com:ct-token-transfer?expand=1)

The bitcoin.com explorer already has an output that is very close to what I want to achieve. Here is a TX where I transferred 100 tokens:
https://explorer.bitcoin.com/bch/tx/9e58fb3424544fd530a3640e8a8f744e735dda5cffe511c09e8909e2fca8010c

Taking the hint above from James Cramer, I was able to produce the following output on my branch:
```
slpOut: { versionType: 1,
  transactionType: 2,
  tokenIdHex:
   'd250f9649646aeaba38e61191f5edcd8dcf2f087a3a71203e1cadf87cc863db4',
  sendOutputs: [ [BigNumber], [BigNumber], [BigNumber], [length]: 3 ] }
slpOut.sendOutputs: [ BigNumber { s: 1, e: 0, c: [Array] },
  BigNumber { s: 1, e: 10, c: [Array] },
  BigNumber { s: 1, e: 16, c: [Array] },
  [length]: 3 ]
slpOut.sendOutputs[0].c: [ 0, [length]: 1 ]
slpOut.sendOutputs[1].c: [ 10000000000, [length]: 1 ]
slpOut.sendOutputs[2].c: [ 999, 99590000000000, [length]: 2 ]
```

So, I can use the `getRawTransaction()` endpoint to retrieve tx details from a txid. I can use `slpjs.parseSlpOutputScript()` to retrieve the token quantities. From here, to complete this endpoint I need to do the following:

- Get expanded tx details from `getRawTransaction()`
- Build up the desired output object by combining the output of `getRawTransaction()` and `slpjs.parseSlpOutputScript()`

**Comment by jcramer** [comment]
I think what you're is proposing is the most efficient rather than trying to use SLPDB. 
 
SLPDB has this information stored within the tokens collection, but you can't query for it directly because it is buried deep.  Each `TokenDBObject` item in the `tokens` collection represents the current state of a valid token's graph.  The item has the following properties:
```
interface TokenDBObject {   
    slpdbVersion: string;
    tokenDetails: SlpTransactionDetailsDb;
    txnGraph: [ txid, GraphTxnDb ][];
    addresses: [ cashAddr, { bch_balance_satoshis: number, token_balance: BigNumber.Object } ][];
    tokenStats: TokenStats | TokenStatsDb;
    lastUpdatedBlock: number;
    tokenUtxos: string[];
}
```

SLPDB will be used to do the following:

- List all address holders (and their balances) of an address (`tokenDBObject. addresses`)
- Get total circulating supply for a token (`tokenDBObject.tokenStats.qty_token_circulating_supply`)
- Get total burned quantity for a token (`tokenDBObject.tokenStats. qty_token_burned `)
- Get **valid** transaction history for a token (`tokenDBObject.txnGraph`)
- Get a list of all valid SLP token IDs (simple mapping of mongo `collections('tokens')`)

Is there anything "major" on this list missing?

Code reference: 
- [TokenDBObject](https://github.com/simpleledger/SLPDB/blob/c4fcbb63a58e53008ba68a62325649be57d26d18/SlpTokenGraph.ts#L509)

**Comment by christroutner** [comment]
I forgot to link to this gist that contains more information on this topic:
https://gist.github.com/christroutner/38f5357345650d201faf7be53ce303c8

**Comment by christroutner** [comment]
@jcramer based on your description above, my gist above, and the discussion we've had on Telegram, it sounds like all the information is there. The **scope** is to *lookup token information by TXID*. The output would contain the following data:

- sentFrom (address) (array?)
- sentTo (array of addresses)
- quantity (probably contained in the arrays for *from* and *to*)
- symbol
- tokenId

**Comment by jcramer** [comment]
@christroutner Do you think it would be acceptable for `sendFrom` array to just be a string list of `[ txid:vout]` or can be represented as a more detailed object like: `[{"idx": number, "txid": string, "vout": number }]`?

The reason being inputs are spent outputs and to avoid data duplication we can just use these references to the spent outputs.

**Comment by christroutner** [comment]
I think that would be fine to limit the scope of the input, especially as a first rev. I know it's not as straightforward as the output.

I see the main value as being in the output data. The input data is nice too, but I can't imagine a strong use-case for it.

**Comment by christroutner** [comment]
PR #327 addresses this Issue. The endpoint is not complete. The data may be changed, but it exists as a live, experimental endpoint.
