### ISSUE TITLE
slp/list/:tokenId is not working for testnet

### ISSUE THREAD

**Issue by christroutner** [Bitcoin-com/rest.bitcoin.com#336]
[This slp/list/:tokenId](https://trest.bitcoin.com/#/slp/listSingle) does not work in testnet. Using txid `0a661f518b2c748d47de90af0365912ba29048b0654ff07032a9ba7783aa02e2` does not return a value, but that TXID can be seen [in this query](https://trest.bitcoin.com/v2/slp/balancesForAddress/qp3sd6m4ry3cm5snu9duzyn5rq0deqt4vgelp5p29j).

Does this endpoint depend on a testnet SLPDB?

The scope of this issue is to investigate why testnet tokenIds are not showing up in trest.

**Comment by cgcardona** [comment]
This is resolved

https://trest.bitcoin.com/v2/slp/list/0a661f518b2c748d47de90af0365912ba29048b0654ff07032a9ba7783aa02e2
