### ISSUE TITLE
Create endpoint to query all token holders

### ISSUE THREAD

**Issue by christroutner** [Bitcoin-com/rest.bitcoin.com#337]
The scope of this Issue is to create a new endpoint in rest that lets users give a Token ID as input and query all the addresses in possession of that token.

This query can be done via SLPDB. Here is [an example query](https://github.com/simpleledger/SLPDB/issues/4) and here is query on slpdb.fountainhead.cash showing [all the holders of the OG token](https://slpdb.fountainhead.cash/explorer2/ewogICJ2IjogMywKICAicSI6IHsKICAgICJkYiI6IFsidCJdLAogICAgImZpbmQiOgogICAgewogICAgICAiJHF1ZXJ5IjoKICAgICAgewogICAgICAgICJ0b2tlbkRldGFpbHMudG9rZW5JZEhleCI6ICI3OTk5NWM0YTgzZWE0OWYwYTZhMzU2Y2U2MDE3ZmYxMDlhYzVlYWE1MmRmNjY4MDIzNGY0ZDI0YWNhZDNmZjU2IgogICAgICB9CiAgICB9LAogICAgInByb2plY3QiOiB7ImFkZHJlc3NlcyI6IDF9LAogICAgImxpbWl0IjogMTAwMAogIH0KfQ==).

**Comment by cgcardona** [comment]
This is resolved w/ https://rest.bitcoin.com/#/slp/balancesForTokenSingle
