### ISSUE TITLE
balancesForAddress returns string when no balance

### ISSUE THREAD

**Issue by m4ktub** [Bitcoin-com/rest.bitcoin.com#390]
When invoking `https://rest.bitcoin.com/v2/slp/balancesForAddress/{address}` the result can be of two types. 

* With balances: `[{"tokenId":"...","balance":...,"slpAddress":"...","decimalCount":0}, ...]`
* Without balances: `"No balance for this address"`

The response has code 200 in both cases and, I believe, this represents regression from a previous behavior where `[]` was returned for an address without balances.

**Comment by cgcardona** [comment]
This is resolved in [PR 486](https://github.com/Bitcoin-com/rest.bitcoin.com/pull/486)
