### ISSUE TITLE
SLP txDetails returns null tokenInfo for some transactions

### ISSUE THREAD

**Issue by m4ktub** [Bitcoin-com/rest.bitcoin.com#407]
The `/v2/slp/txDetails` endpoint has an incosistent output. For some SLP SEND transactions `tokenInfo` contains information while for others it does not. Encountered the error while loading the [SLP Torch trail](https://m4ktub.github.io/bch-torch/) which makes use of that information.

Example of a sequence of spends where one of the transactions shows this problem:
1. `tokenInfo` != null for [4f29...d773](https://rest.bitcoin.com/v2/slp/txDetails/4f29ae7bde72c1140df2df5c70ddc4709c2cbbf243a9963413cd58925f63d773)
2. `tokenInfo` == null for [23c3...1848](https://rest.bitcoin.com/v2/slp/txDetails/23c3c4c21d2f03996327072a71ea309d0bbf9db57a28c1714209df530ab51848)
3. `tokenInfo` != null for [c5ab...110c](https://rest.bitcoin.com/v2/slp/txDetails/c5abe6cf0baa60bd49bf7e130cc5284271a1d605256cb4d8beccf950e1ea110c)

While looking for a pattern, the only theory I have is that this occurs for transactions where all outputs are spent because I could spot the same issue in [6f77...5169](https://rest.bitcoin.com/v2/slp/txDetails/6f77b60d1a04b57c686c7bbbe29184b749658a5a949c608a6dcbb59d71695169).

**Comment by cgcardona** [comment]
This is no longer reproducible. If you see it again please re-open this issue. Thanks!
