### ISSUE TITLE
Problems with /block/detailsByHash

### ISSUE THREAD

**Issue by christroutner** [Bitcoin-com/rest.bitcoin.com#409]
Leaving this here so I remember to look into it when I get back from vacation.

AllanYesterday at 9:15 AM
I have an issue with bitbox that seems to be caused by trest.bitcoin.com.  I request the best block hash, then use the block hash to request the block and I get "error": "Not found". This can be easily replicated on trest.bitcoin.com with blockchain/getBestBlockHash, then /block/detailsByHash. Anyone else have this issue/know of a fix?

chris.troutnerYesterday at 1:56 PM
You're right @Allan. I can confirm something fishy is happening there. I used the hash for block # 1304056 on testnet: 00000000000004889bf5cdf8bf56d5dcf67edb65e6783c07f57d68e06ef9249f

rest.bitcoin.com is returning an error for that hash:
https://trest.bitcoin.com/v2/block/detailsByHash/00000000000004889bf5cdf8bf56d5dcf67edb65e6783c07f57d68e06ef9249f

**Comment by christroutner** [comment]
I'm getting new, strange errors from the testnet Insight API when using bch-cli-wallet. I believe the error in this issue is also due to the testnet Insight API. 

The BITBOX team is currently working on getting the code needed to run BCH Insight API post fork. That will be the first step towards approaching this Issue.

**Comment by cgcardona** [comment]
@christroutner I'm unable to reproduce this. Could it have been an issue w/ our previous insight backend which was causing issues immediately after the fork? 

Best Block Hash: https://trest.bitcoin.com/v2/blockchain/getBestBlockHash 

```
00000000003326f23dc30f646cad31534968168cdd81b5fcad200f239bee0da2
```

Block Details by Hash https://trest.bitcoin.com/v2/block/detailsByHash/00000000003326f23dc30f646cad31534968168cdd81b5fcad200f239bee0da2

```js
{
"hash": "00000000003326f23dc30f646cad31534968168cdd81b5fcad200f239bee0da2",
"size": 1737,
"height": 1317508,
"version": 536870912,
"merkleroot": "88037868bd0c549f8b6725727e48adfabb31f9739461e1d8849cd71ca2c6da18",
"tx": [
"f380c7107860c617e4f2ab7737e317d1d632376aec0dbced0df81f3ed419b728",
"469ae37a3c7c870b8f20849ac77bac0efea9da336c48e236c235e4515e2badfa",
"51d360a6b89f29e090fcd665bda6161986a3c155fcc4d4f2b48ae83a966da23f",
"7e8ed09e171a7a0870f088f1d2319103def0651f38cf9a4bef6eaa74babcbc5a",
"c33746db2d9a2b3d04eb2ec85607b36f3414d1dd5dff6c3a5d265ae4af1245b3"
],
"time": 1564245287,
"nonce": 3349396032,
"bits": "1b3e285c",
"difficulty": 1054.33516203,
"chainwork": "00000000000000000000000000000000000000000000005112ae79e839218f58",
"confirmations": 1,
"previousblockhash": "00000000001c3a052beaa897c1651821c7767882ad4e51cf3b56fcfa5f8d0b12",
"reward": 0.78125,
"isMainChain": true,
"poolInfo": {}
}
```

**Comment by christroutner** [comment]
This issue appears to have been fixed by switching to our team-controlled instance of testnet Insight API.
