### ISSUE TITLE
Testnet Insight queries are being rate limited

### ISSUE THREAD

**Issue by christroutner** [Bitcoin-com/rest.bitcoin.com#418]
Requesting less than 20 addresses in `/v2/address/details` returns a rate limiting error from the Insight API. Here is an example curl statement:

## Steps to reproduce
1. Access the POST bulk endpoint on trest:

https://trest.bitcoin.com/#/address/detailsBulk

2. Use an array of addresses less than 20:
```
{
  "addresses": [
    "bchtest:qzjtnzcvzxx7s0na88yrg3zl28wwvfp97538sgrrmr",
    "bchtest:qp6hgvevf4gzz6l7pgcte3gaaud9km0l459fa23dul",
    "bchtest:qp5jd4qgvq5k0xqxa78hwunrkdzl0rhdqukdmgxef8",
    "bchtest:qpkgvhcatvrvnu258p67r32mfwp6d92geuyg3na29m",
    "bchtest:qp2wgkrzljqat7s34g7wulmq7mgrqk4hyuammymrvc",
    "bchtest:qp9gmfllg3feme32m93uwnzrld44zsf27ssqj7qunw",
    "bchtest:qpr6nfy5g2a82cxwpj58lca8vn8vzwkfvszgqc9zez",
    "bchtest:qpcrtam4jj559ftaax4yvwyr8zc0al3mcqv56jjqg5",
    "bchtest:qqgkq8n5h5h7z30uj48fqtnf92nguhyh9utwtl5507",
    "bchtest:qp9gmfllg3feme32m93uwnzrld44zsf27ssqj7qunw",
    "bchtest:qpkgvhcatvrvnu258p67r32mfwp6d92geuyg3na29m",
    "bchtest:qz9xmpjkkcpl7w9uwmefnzgtwmprlj7c25erzqpa2l",
    "bchtest:qps39g8hd96sqe80psuettutpqg523j4cgv9cmstfw",
    "bchtest:qp8z9whnrsfpnz3nt3cnp2g08hsmnq3qfv995vg5aq",
    "bchtest:qzmx4dy03lz8fuv3e08r5x72hmqqnvmu3qgmhfzkc7"
  ]
}
```

3. Observe the following error message:

`{ "error": "Bitcoin JSON-RPC: Work queue depth exceeded. Code:429" }`

**Comment by christroutner** [comment]
The issue does not always present itself, probably because of the load balancers. Sometimes the results will return successfully, sometimes with the error above, and sometimes a 504 gateway error.

**Comment by cgcardona** [comment]
Confirmed this is still reproducible.

**Comment by christroutner** [comment]
This issue has been fixed by point trest to our own team-controlled instance of Insight API.
