### ISSUE TITLE
Create SLP Endpoints 

### ISSUE THREAD

**Issue by cgcardona** [Bitcoin-com/rest.bitcoin.com#56]
This is blocked by https://github.com/Bitcoin-com/rest.bitcoin.com/issues/58

* ~~`/list`~~
* ~~`/list/:txid`~~
* ~~`/balance/{address}/{id}`~~
* ~~`balancesForAddress/{address}`~~
* `balancesForId/{id}`
* ~~`address/convert/{address}`~~

**Comment by SpendBCH** [comment]
For balancesForId we can use slp-balances https://github.com/SpendBCH/slp-balances

**Comment by cgcardona** [comment]
This is complete!
