### ISSUE TITLE
Add logging

### ISSUE THREAD

**Issue by cgcardona** [Bitcoin-com/rest.bitcoin.com#59]
Integrate https://www.npmjs.com/package/graylog2 for logging.

**Comment by christroutner** [comment]
This logging  library is incorporated in the code base and provides all the hooks we'll need to incorporate logging:
https://github.com/Bitcoin-com/rest.bitcoin.com/blob/master/src/routes/v2/logging.js

**Comment by christroutner** [comment]
We have implemented local logging, but it's extremely limited. Leaving this issue open as we still need a long-term logging solution.
